### ISSUE TITLE
发现关于Object.prototype.hasOwnProperty的小错误

### ISSUE THREAD

**Issue by niki571** [bicycleChen/Polyfills#1]
对于对象，则使用for(let key in obj)，因为for i in只遍历可枚举的属性，所以在使用for i in的时候，一定要用Object.prototype.hasOwnProperty来确保获得的是枚举属性。另外，for i in 有可能导致disorder。

这句错了。。。
用Object.prototype.hasOwnProperty，是因为for...in会遍历原型链属性，而Object.prototype.hasOwnProperty可以用来判断是否是对象自身属性而筛选掉原型链属性～

**Comment by bicycleChen** [comment]
欧凯！谢谢小天使的纠正！我改一下😄

**Comment by niki571** [comment]
还是有问题，Object.prototype.hasOwnProperty是枚举不可枚举都可以的

**Comment by bicycleChen** [comment]
明白了！！谢谢小天使！

**Comment by bicycleChen** [comment]
已修改～是for i in 只能严格用于可枚举属性，但hasOwnProperty 既可用于枚举，也可用于非枚举，感谢小天使 🙋
